// src/components/Nav.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'

export default function Nav() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  const navItems = [
    { href: '/', label: 'Home' },
    { href: '/about', label: 'About' },
    { href: '/robot', label: 'Robot' },
    { href: '/sponsors', label: 'Sponsors' },
    { href: '/contact', label: 'Contact' },
  ]

  return (
    <nav className="sticky top-0 z-50 bg-background border-b border-border shadow-lg">
      <div className="container">
        <div className="flex justify-between items-center py-4">
          <Link href="/" className="text-2xl font-bold text-primary">
            FRC Team 10951
          </Link>
          
          {/* Desktop Menu */}
          <ul className="hidden md:flex gap-8">
            {navItems.map((item) => (
              <li key={item.href}>
                <Link
                  href={item.href}
                  className="text-text hover:text-primary transition-colors font-medium"
                >
                  {item.label}
                </Link>
              </li>
            ))}
          </ul>

          {/* Mobile Menu Toggle */}
          <button
            className="md:hidden flex flex-col gap-1.5"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle menu"
          >
            <span
              className={`w-6 h-0.5 bg-text transition-all ${
                mobileMenuOpen ? 'rotate-45 translate-y-2' : ''
              }`}
            />
            <span
              className={`w-6 h-0.5 bg-text transition-all ${
                mobileMenuOpen ? 'opacity-0' : ''
              }`}
            />
            <span
              className={`w-6 h-0.5 bg-text transition-all ${
                mobileMenuOpen ? '-rotate-45 -translate-y-2' : ''
              }`}
            />
          </button>
        </div>

        {/* Mobile Menu */}
        <div
          className={`md:hidden overflow-hidden transition-all duration-300 ${
            mobileMenuOpen ? 'max-h-64' : 'max-h-0'
          }`}
        >
          <ul className="flex flex-col gap-4 py-4 border-t border-border">
            {navItems.map((item) => (
              <li key={item.href}>
                <Link
                  href={item.href}
                  className="block text-text hover:text-primary transition-colors font-medium"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  {item.label}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </nav>
  )
}

// src/lib/components/Nav.svelte
<script>
	let mobileMenuOpen = false;

	const navItems = [
		{ href: '/', label: 'Home' },
		{ href: '/about', label: 'About' },
		{ href: '/contact', label: 'Contact' },
	];
</script>

<nav class="sticky top-0 z-50 bg-background border-b border-border shadow-lg">
	<div class="container">
		<div class="flex justify-between items-center py-4">
			<a href="/" class="text-2xl font-bold text-primary"> Your Website </a>

			<!-- Desktop Menu -->
			<ul class="hidden md:flex gap-8">
				{#each navItems as item}
					<li>
						<a href={item.href} class="text-text hover:text-primary transition-colors font-medium">
							{item.label}
						</a>
					</li>
				{/each}
			</ul>

			<!-- Mobile Menu Toggle -->
			<button
				class="md:hidden flex flex-col gap-1.5"
				on:click={() => (mobileMenuOpen = !mobileMenuOpen)}
				aria-label="Toggle menu"
			>
				<span
					class="w-6 h-0.5 bg-text transition-all"
					class:rotate-45={mobileMenuOpen}
					class:translate-y-2={mobileMenuOpen}
				/>
				<span class="w-6 h-0.5 bg-text transition-all" class:opacity-0={mobileMenuOpen} />
				<span
					class="w-6 h-0.5 bg-text transition-all"
					class:-rotate-45={mobileMenuOpen}
					class:-translate-y-2={mobileMenuOpen}
				/>
			</button>
		</div>

		<!-- Mobile Menu -->
		<div
			class="md:hidden overflow-hidden transition-all duration-300"
			class:max-h-64={mobileMenuOpen}
			class:max-h-0={!mobileMenuOpen}
		>
			<ul class="flex flex-col gap-4 py-4 border-t border-border">
				{#each navItems as item}
					<li>
						<a
							href={item.href}
							class="block text-text hover:text-primary transition-colors font-medium"
							on:click={() => (mobileMenuOpen = false)}
						>
							{item.label}
						</a>
					</li>
				{/each}
			</ul>
		</div>
	</div>
</nav>
